steps:

#
# Build our binary
#  
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
  env: ['PROJECT_ROOT=gcp-petstore']

#
# Build the docker image
#
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-petstore:$REVISION_ID', '-f', 'Dockerfile', '.']

images:
  - 'gcr.io/$PROJECT_ID/gcp-petstore'