steps:

#
# Install dependencies (doesn't need to be a separate step)
#  
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', '.']
  env: ['PROJECT_ROOT=petstore']

#
# Build the binary
#
- name: 'gcr.io/cloud-builders/go:alpine'
  #args: ['install', 'github.com/pentaphobe/gcp-petstore']
  entrypoint: 'sh'
  args:
    - -c
    - |
      # go install github.com/pentaphobe/gcp-petstore
      echo 'in go:alpine...'      
      echo $PROJECT_ID $REVISION_ID  
      go build ./main.go
      ls -al
  env: ['PROJECT_ROOT=petstore']

#
# Build the docker image
#
- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-petstore:$REVISION_ID', '-f', 'Dockerfile', '.']
  entrypoint: 'sh'
  args:
    - -c
    - |
      echo 'in docker...'
      echo $REVISION_ID
      ls -al
      docker build -t gcr.io/$PROJECT_ID/gcp-petstore:$REVISION_ID .

images:
  - 'gcr.io/$PROJECT_ID/gcp-petstore:$REVISION_ID'